language: node_js
os: linux
sudo: false
jdk: oraclejdk8

# addons:
#   apt:
#    packages:
#     - oracle-java8-installer

node_js:
  - "node"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version

install:
  - npm install
  - npm run cassandra-start
  - sleep 30


script:
  - gulp test

after_success:
  - echo "+++ SUCCESS +++"

after_failure:
  - echo "-- FAILURE ---"

after_script:
  - npm run cassandra-stop
